name: Release Obsidian plugin

on:
  push:
    tags:
      - "*"  # Triggers workflow on any tag push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: npm install

      - name: Build plugin
        run: npm run build

      - name: Archive plugin files
        run: |
          zip obsidian-slide-improvements-${GITHUB_REF##*/}.zip main.js manifest.json styles.css || true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: true
          files: |
            main.js
            manifest.json
            styles.css
            obsidian-slide-improvements-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}